const store = [
  {
    object: "glass shards",
    price: 1.13,
    description: "probably not edible",
    imageUrl: "/glassshards.png",
    avaliability: "LAST ONE!! DON'T MISS OUT",
    altText: "glass shards",
  },
  {
    object: "feesh",
    price: 106.78,
    description: "one singular feesh",
    imageUrl: "/feesh.png",
    avaliability: "OUT OF STOCK",
    altText: "fish",
  },
  {
    object: "19 6 pc mcnuggets boxes",
    price: 25.82,
    description: "the edible has been eaten so not edible",
    imageUrl: "/MCNUGGIES.png",
    avaliability: "IN STOCK",
    altText: "19 chicken nugget boxes with x's over the chicken nuggets",
  },
  {
    object: "micro kitten",
    price: 0.001,
    description: "not even worth a cent or the size of a cent",
    imageUrl: "/microkitten.png",
    avaliability: "maybe in stock, idk",
    altText: "a kitten is shown next to a penny",
  },
  {
    object: "the pen you lost 234 days ago",
    price: 234.0,
    description: "it's also missing the spring, you have it though",
    imageUrl: "/pen.png",
    avaliability: "OUT OF STOCK",
    altText: "a grey line, meant to represent a pen",
  },
  {
    object: "the screams of the tortured",
    price: 64.05,
    description: "aka tech students' cries, neatly packed in pandora's box",
    imageUrl: "SCREAMS.png",
    avaliability: "IN STOCK",
    altText: "red text displaying A's all over the page",
  },
  {
    object: "assorted trinkets",
    price: 104.029,
    description: "selling this poor crow's home because he forgot to pay rent",
    imageUrl: "/trinkets.png",
    avaliability: "IN STOCK",
    altText: "assortment of colorful lines and sparkles",
  },
  {
    object: "used batteries",
    price: 200.04,
    description: "no power guaranteed",
    imageUrl: "/batteries.png",
    avaliability: "LAST ONE!! DON'T MISS OUT",
    altText: "battery exploded",
  },
  {
    object: "playing card set",
    price: 51.51,
    description:
      "but one of the cards is missing but its a different card every time you check",
    imageUrl: "/cards.png",
    avaliability: "OUT OF STOCK",
    altText: "showing 5 Aces in card stack",
  },
  {
    object: "live ww1 stick grenade",
    price: 248.01,
    description: "the real thing!",
    imageUrl: "stickgrenade.png",
    avaliability: "IN STOCK",
    altText:
      "image with text saying 'i'm going to be real idk what a stick grenade is i didnt even know that they existed until someone told me'",
  },
  {
    object: "a singular beanboozled",
    price: 320.0,
    description: " HUH ???????????????",
    imageUrl: "beanboozled.png",
    avaliability: "maybe in stock, idk",
    altText: "confused cat",
  },
  {
    object: "watermelon rind",
    price: 314.15,
    description: "it's intact.",
    imageUrl: "/rind.png",
    avaliability: "maybe in stock, idk",
    altText: "green, slightly bent line",
  },
  {
    object: "glass of water",
    price: 31.09,
    description: "stolen from a painter",
    imageUrl: "/water.png",
    avaliability: "OUT OF STOCK",
    altText: "glass of paint water",
  },
  {
    object: "chip bag",
    price: 10.23,
    description: "99.99% air, that 0.01 is a mystery",
    imageUrl: "/chip bag.png",
    avaliability: "IN STOCK",
    altText: "'it's literally all air'",
  },
  {
    object: "chapstick",
    price: 25.44,
    description: "for people who won't shut up",
    imageUrl: "/chaptick.png",
    avaliability: "LAST ONE!! DON'T MISS OUT",
    altText: "gluestick labeled as chapstick",
  },
  {
    object: "screwdriver",
    price: 23.41,
    description: "but more like circle driver",
    imageUrl: "/screwdriver.png",
    avaliability: "OUT OF STOCK",
    altText: "screwdriver, with end edited to just be a circle",
  },
  {
    object: "grocery store coupons",
    price: 234.43,
    description: "guaranteed to have been expired yesterday",
    imageUrl: "/coupon.png",
    avaliability: "OUT OF STOCK",
    altText: "coupon for 200% off that expired yesterday",
  },
  {
    object: "nuclear launch codes",
    price: 123.43,
    description:
      "OUTDATED. i promise a cat did not run over a keyboard and we just sold these",
    imageUrl: "/LAUNCH CODE.png",
    avaliability: "IN STOCK",
    altText: "3 blurred codes for nuclear launch codes",
  },
  {
    object: "smart boosters",
    price: 85.65,
    description:
      "did not steal this product from another store at all whaaaaaat",
    imageUrl: "/smart boosters.png",
    avaliability: "maybe in stock, idk",
    altText:
      "someone asking for image of smart boosters, getting response that they are actually cyanide pills",
  },
  {
    object: "eyes lost to this website",
    price: 110.01,
    description: "sorry (not really)",
    imageUrl: "/eyes.png",
    avaliability: "OUT OF STOCK",
    altText: "eyeballs, crying",
  },
];

export { store };
