const store = [
  {
    object: "glass shards",
    price: "1.13",
    description: "probably not edible",
    imageUrl: "/OIP.jfif",
    avaliability: "last one",
  },
  {
    object: "feesh",
    price: "106.78",
    description: "one singular feesh",
    imageUrl: "",
    avaliability: "n",
  },
  {
    object: "19 6 pc mcnuggets boxes",
    price: "2.82",
    description: "the edible has been eaten so not edible",
    imageUrl: "",
    avaliability: "y",
  },
  {
    object: "micro kitten",
    price: "0.001",
    description: "not even worth a cent or the size of a cent",
    imageUrl: "",
    avaliability: "maybe",
  },
  {
    object: "the pen you lost 234 days ago",
    price: "234.00",
    description: "it's also missing the spring, you have it though",
    imageUrl: "",
    avaliability: "n",
  },
  {
    object: "the screams of the tortured",
    price: "6.05",
    description: "aka tech students' cries, neatly packed in pandora's box",
    imageUrl: "",
    avaliability: "y",
  },
  {
    object: "assorted trinkets",
    price: "10.029",
    description: "selling this poor crow's home because he forgot to pay rent",
    imageUrl: "",
    avaliability: "y",
  },
  {
    object: "used batteries",
    price: "200.04",
    description: "no power guaranteed",
    imageUrl: "",
    avaliability: "last one",
  },
  {
    object: "playing card set",
    price: "51.51",
    description:
      "but one of the cards is missing but its a different card every time you check",
    imageUrl: "",
    avaliability: "n",
  },
  {
    object: "live ww1 stick grenade",
    price: "0.01",
    description: "the real thing!",
    imageUrl: "",
    avaliability: "y",
  },
  {
    object: "a singular beanboozled",
    price: "1239218309128490.23",
    description:
      "?????????????????????????????? HUH ???????????????????????????????",
    imageUrl: "",
    avaliability: "maybe",
  },
  {
    object: "watermelon rind",
    price: "3141.59",
    description: "it's intact.",
    imageUrl: "",
    avaliability: "maybe",
  },
  {
    object: "glass of water",
    price: "1.09",
    description: "stolen from a painter",
    imageUrl: "",
    avaliability: "no",
  },
  {
    object: "chip bag",
    price: "10.23",
    description: "99.99% air, that 0.01 is a mystery",
    imageUrl: "",
    avaliability: "y",
  },
  {
    object: "chapstick",
    price: "25.43",
    description: "for people who won't shut up",
    imageUrl: "",
    avaliability: "last one",
  },
  {
    object: "screwdriver",
    price: "23.41",
    description: "but more like circle driver",
    imageUrl: "",
    avaliability: "n",
  },
  {
    object: "grocery store coupons",
    price: "234.43",
    description: "guaranteed to have been expired yesterday",
    imageUrl: "",
    avaliability: "n",
  },
  {
    object: "nuclear launch codes",
    price: "1234.3",
    description:
      "OUTDATED. i promise a cat did not run over a keyboard and we just sold these",
    imageUrl: "",
    avaliability: "y",
  },
  {
    object: "smart boosters",
    price: "85.65",
    description:
      "did not steal this product from another store at all whaaaaaat",
    imageUrl: "",
    avaliability: "maybe",
  },
  {
    object: "eyes lost to this website",
    price: "10.01",
    description: "sorry (not really)",
    imageUrl: "",
    avaliability: "n",
  },
];

export { store };
